# Generated by Django 3.0.6 on 2020-05-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='url1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
