# Generated by Django 3.0.6 on 2020-05-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jops', '0002_auto_20200517_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date',
            new_name='job_date',
        ),
    ]
