# Generated by Django 3.0.6 on 2020-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jops', '0004_auto_20200517_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='url1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
