# Generated by Django 3.0.6 on 2020-05-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jops', '0005_auto_20200517_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_date',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url1',
        ),
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
