# Generated by Django 3.0.6 on 2020-05-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jops', '0007_auto_20200517_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
